UBCSailbot/sailbot_workspace

- .devcontainer/base/Dockerfile
- .devcontainer/base/install-ompl-ubuntu-python3.sh
- .devcontainer/base/raye/Dockerfile
- .devcontainer/base/raye/install-ompl-ubuntu-python2.sh
- .devcontainer/base/raye/install-raye-dependencies.bash
- .devcontainer/dev/Dockerfile
- .devcontainer/dev/update_bashrc_ros.sh
- .github/workflows/build-dev-image.yaml
Based on devcontainer configuration from https://github.com/patrick-5546/sailbot_ros2_workspace/tree/main/.devcontainer
> Add base and dev image files

- .devcontainer/Dockerfile
- .devcontainer/dev/Dockerfile
- .devcontainer/dev/update-bashrc.sh
* Resolves #19 
* Also adds software that makes the git experience better: less, git-delta
> Add descriptions to aliases and git-related software

- .devcontainer/Dockerfile
- .devcontainer/README.md
- .devcontainer/dev/README.md
- Clarified what needs to be done to update dev and devcontainer images
> Update devcontainer documentation

- .devcontainer/.dockerignore
- .devcontainer/Dockerfile
- .devcontainer/config/README.md
- .devcontainer/config/sailbot_workspace.code-workspace
- .devcontainer/dev/Dockerfile
- .gitignore
- README.md
The workspace file allows for [multi-root workspaces](https://code.visualstudio.com/docs/editor/multi-root-workspaces), which makes it easier to edit multiple ROS nodes at once
Other changes
- Update main README
- Fix ROS 1 workspace file permissions
> Create workspace file

- .devcontainer/config/sailbot_workspace.code-workspace
To try out this fix:
1. Checkout to this branch: `git switch patrick-5546/fix-tasks`
2. Open the workspace
1. Open `.devcontainer/config/sailbot_workspace.code-workspace` in VS Code
2. Click "Open Workspace"
3. Try running the task
> Fix create new package with a node tasks

- .devcontainer/devcontainer.json
> Create Docker volume for ROS 1 workspace

- .clang-format
- .clang-tidy
- .devcontainer/Dockerfile
- .devcontainer/config/sailbot_workspace.code-workspace
- .devcontainer/dev/Dockerfile
- .devcontainer/devcontainer.json
- .github/actions/lint/run.sh
- .github/actions/test/run.sh
- .github/workflows/lint.yaml
- .gitignore
- .vscode/c_cpp_properties.json
- build.sh
- run_clang-tidy.sh
- src/new_project.repos
Update the workspace to utilize the C++ tools outlined [here](https://ubcsailbot.github.io/docs/reference/cpp/tools/) in conjunction with the [Network Systems repository](https://github.com/UBCSailbot/network_systems/tree/main).
Closes #38 
Tasks remaining:
> Add C++ dependencies and configuration files

- .markdown-link-check.json
Was failing markdownlinkcheck CI
> Ignore distrowatch links

- .devcontainer/devcontainer.json
- README.md
Resolves #45
Came up with a janky workaround, using the fact that VS Code thinks DISPLAY is 1 when set. Will have to revert this workaround if this Windows 10 + WSL 2 Docker + VS Code bug is ever fixed.
Resources
- https://stackoverflow.com/questions/6594085/remove-first-character-of-a-string-in-bash
> Automate Windows 10 x11 forwarding

- .devcontainer/config/sailbot_workspace.code-workspace
- .devcontainer/devcontainer.json
- Resolves #54
I realise last time that I had my changes to docs done & reviewed & merged to main, but I forgot to upload my local branch created for sailbot_workspace, oops
> VS Code Configuration Improvements Tracker - flake8 & whitespace

- setup.sh
Regression from changes made in #73
> Fix setup regression

- .github/release.yml
- Resolves #43
- Updated `release.yml` to contain more in-depth release notes.
- To preview the notes, draft a release using the branch `user/dfriend01/43-autogen-release-notes` as the target branch. Currently, it only shows Docker changes since there was only PRs with docker changes so far.
> Update release note template

- .clang-format
- .clang-tidy
- .devcontainer/devcontainer.json
Small changes to formatting rules and static analysis. Also adding an extension for easier and more consistent inline documentation.
> Update configs for NET

- .devcontainer/Dockerfile
Verify CI passes when implementing changes from #85. Needed to merge to main first so that workflow could be run on workflow dispatch
> Test Base Dev Workflow

- .devcontainer/devcontainer.json
- For some background, see https://github.com/UBCSailbot/sailbot_workspace/issues/71#issuecomment-1404792827
- Works on my laptop (Windows 11)
> Fix X11 Forwarding

- .devcontainer/config/sailbot_workspace.code-workspace
- .devcontainer/devcontainer.json
- run_clang-tidy.sh
- src/new_project.repos
Applies the devcontainer.json changes in the following PRs:
- #90 
- #86
> Raye: update devcontainer.json with main

- .devcontainer/base-dev/README.md
- .devcontainer/devcontainer.json
- .devcontainer/pre-base/README.md
Small stuff: reorganization, clarifications, etc.
> Update dev container documentation

- .github/release.yml
> Add Documentation Update section in

- README.md
- Done as part of #UBCSailbot/docs#111
> Link to documentation on docs site

- .github/workflows/tests.yml
> Add ament_pep257 to Tests workflow

- .github/workflows/tests.yml
- README.md
Double quotes in multiple layers. Removed the outer double quote, as it isn't required
- Continuation of #96 
- Rebuild docs job doesn't run in PR
- Will have to push to main to verify if this PR has successfully fixed the rebuild docs job
- README should be updated in https://ubcsailbot.github.io/docs/current/sailbot_workspace/overview/
> Fix rebuild docs job

- .github/workflows/tests.yml
- Follow up to #100, which resolves https://github.com/UBCSailbot/network_systems/issues/11
> Call test definitions workflow in main branch

- .devcontainer/Dockerfile
- .devcontainer/base-dev/base-dev.Dockerfile
- .devcontainer/config/sailbot_workspace.code-workspace
- .github/actions/ament-lint/run.sh
- build.sh
- src/new_project.repos
- test.sh
Satellite hardware emulation.
- Emulates the network data flow from Local Transceiver <-> Remote Transceiver.
- Serial communication
- HTTP communication
- Eliminates the need for a separate mock Local/Remote Transceiver implementation
- See https://github.com/UBCSailbot/network_systems/pull/26 for a the script that automates the process of running virtual iridium
- See https://github.com/UBCSailbot/network_systems/tree/virtual-iridium-setup/scripts#run-virtual-iridium
*Note*: This PR modifies the workflow to exclude the virtual_iridium repository in lint checks because it's a legacy codebase made for Python2. Refactoring it for Python3 is not worth the investment.
> Setup virtual iridium

- .devcontainer/config/sailbot_workspace.code-workspace
- src/new_project.repos
- No issue assigned, tasks are on https://ubcsailbot.atlassian.net/wiki/spaces/prjt22/pages/edit-v2/1798504659
- Relevant PR: https://github.com/UBCSailbot/ros_msgs/pull/2
- Refer to verification of ros_msgs within other PR
> Added https://github.com/UBCSailbot/ros_msgs

- .devcontainer/docker-compose.yml
Improve performance of docker volumes
- https://tkacz.pro/docker-volumes-cached-vs-delegated/
> Make docker volumes delegated

- .devcontainer/config/sailbot_workspace.code-workspace
- .devcontainer/devcontainer.json
- .devcontainer/docker-compose.yml
- .devcontainer/website/website.Dockerfile
- src/new_project.repos
Replaces #107, which was getting too big and messy. This PR adds the website repository https://github.com/UBCSailbot/website, and other potential solutions for the website, in separate containers.
Usage instructions can be found in the old PR: https://github.com/UBCSailbot/sailbot_workspace/pull/107#issuecomment-1481966571
> Add potential solutions for the website v2

- .github/workflows/test_definitions.yml
- .github/workflows/tests.yml
> Fix rebuild docs part 3

- .devcontainer/README.md
- .devcontainer/base-dev/README.md
- .devcontainer/docs/README.md
- .devcontainer/pre-base/README.md
- .devcontainer/website/README.md
Update with changes since #115
> Update dev container docs

- .devcontainer/docs/README.md
- .devcontainer/website/README.md
> Update features of docs and website images

- .devcontainer/config/sailbot_workspace.code-workspace
- .github/actions/ament-lint/run.sh
- src/new_project.repos
Will be heavily referenced in the development of the local_pathfinding repo. So that CI passes, using a special branch with ROS files and excluding it from `ament_flake8` checks.
> Add raye-local-pathfinding repo to workspace

- .devcontainer/config/sailbot_workspace.code-workspace
- .devcontainer/devcontainer.json
- Format whitespace on save
- Add todo tree extension
- Organize settings
> Update VS Code configuration

- setup.sh
Before this PR if you were working in a branch different than the one specified in `new_project.repos` you would switch branches. Now the setup task will skip existing directories.
> Skip existing directories when setting up

- .devcontainer/Dockerfile
- .devcontainer/config/sailbot_workspace.code-workspace
- test.sh
- Set up VS Code Pytest integration: can run tests from Testing sidebar
- Show test outputs when ROS tests
- Unrelated: reorganize `.devcontainer/Dockerfile`
> Improve Python testing infrastructure

- .devcontainer/config/sailbot_workspace.code-workspace
- .devcontainer/devcontainer.json
- Resolves most of #6 
- Old PR where C++ launch configs were being investigated: #58 
The [ROS extension](https://marketplace.visualstudio.com/items?itemName=ms-iot.vscode-ros) adds cool features such as debugging (launching and attaching to ROS nodes), running or launching nodes interactively, syntax highlighting for msg files, and formatting/autocomplete.
Currently supported debug configs:
- Attach
-  C++ nodes
- Python nodes are a known issue: https://github.com/ms-iot/vscode-ros/issues/872
- Launch
- Launch files
- C++ nodes
I fixed the formatting of the workspace file, which messes up the diff. To see the actual diff, exclude the first 2 commits.
- https://github.com/ms-iot/vscode-ros/blob/master/doc/debug-support.md#attach
> Improve debugging experience

- .github/workflows/test_definitions.yml
Need to update the workflow file rebuild-docs is running after changes to the CI in the docs site from https://github.com/UBCSailbot/docs/pull/144
> Fix rebuild docs

- .devcontainer/Dockerfile
- .devcontainer/base-dev/update-bashrc.sh
- Continuation of #140 
- Existing flow: if underlay+overlay found source, else source overlay
- New flow: source overlay, source underlay if found
Also improved warning message
> Update ROS sourcing

- .github/workflows/test_definitions.yml
- Resolves the bug where CI was trying to refer to a non-existent branch for custom interfaces
- CI on this PR should be passing
> Remove references to old custom interfaces branch and change to main

- .github/workflows/test_definitions.yml
- .github/workflows/tests.yml
In the custom_interfaces repo, it is checked out twice. Adds check to custom_interfaces checkout step.
> Fix redundant custom interfaces

- .devcontainer/Dockerfile
Previously their permissions were root, meaning that they couldn't be modified without sudo.
> Maker user owner of dotfiles

- .devcontainer/config/sailbot_workspace.code-workspace
- When debugging tests with the testMate extension, sailbot_workspace would build twice
-
> Fix C++ debug config

- build.sh
- Last commit to build.sh changed the way arguments were passed, which broke the passing of the BUILD_TYPE flag.
-
> Restore BUILD_TYPE Flag

- .devcontainer/Dockerfile
- .devcontainer/base-dev/base-dev.Dockerfile
> Add local pathfinding python dependencies

- .devcontainer/devcontainer.json
- .devcontainer/website/website.Dockerfile
- ~~Port forward the mongodb container~~
- Fix updating dependencies
- Add cucumber.js extension for website tests
- Run the `website` and `db` containers. 
- Ensure that `MONGODB_URI` is set to `mongodb://localhost:27017` within `.env.local` in the website repo.  
- Go to the URL `http://localhost:3005/api/gps`. You should expect the following response `{success: true, data: [ ]}` if the website connected to the database successfully. 
-
> Website infrastructure updates

- .devcontainer/devcontainer.json
- .devcontainer/docker-compose.yml
- It's better to have the connection string be a parameter so we can decide where to connect at run-time (i.e. testing vs deployment).
- Mongodb running is required for network systems tests to pass
> Run mongodb by default

- src/global_launch/config/README.md
- src/global_launch/config/globals.yaml
- src/global_launch/main_launch.py
- Resolves https://github.com/UBCSailbot/boat_simulator/issues/37
- Implementation of reading these parameters in the `boat_simulator` is done in https://github.com/UBCSailbot/boat_simulator/pull/43
- [ROS2 YAML parameter structure](https://roboticsbackend.com/ros2-yaml-params/#Why_using_YAML_for_ROS2_params)
- [ROS2 Parameter docs](https://docs.ros.org/en/humble/Concepts/Basic/About-Parameters.html)
> ROS Parameters: Add boat simulator ROS parameters

- .github/workflows/test_definitions.yml
- .github/workflows/tests.yml
> Add run-sailbot-workspace-ci job

- .devcontainer/config/sailbot_workspace.code-workspace
- src/polaris.repos
Created a repo for the diagnostics app. This PR integrates it with the sailbot workspace.
> Add diagnostics repo to sailbot workspace

- .github/workflows/test_definitions.yml
Currently it's always cloning the main branch of sailbot workspace. We want it to clone the version that is referenced by the caller workflow.
- https://github.com/actions/toolkit/issues/1264
> Fix sailbot workspace ref in CI

- .devcontainer/devcontainer.json
- .devcontainer/docker-compose.website.yml
Not planning to use it for the website anymore, planning to make a custom data dashboard
> Remove Grafana

- .github/workflows/build-images.yml
- .github/workflows/test_definitions.yml
Add a timeout for each job, because if something runs for much longer than usual there's probably something wrong.
@hhenry01 do these timeouts look reasonable to you?
- https://stackoverflow.com/a/59076067
> Add timeout to each CI test

- .gitignore
To grey out a directory in the vs code explorer, need to remove `*` at the end of directories. This is only required if you want to exclude files in that directory from being ignored.
> Fix gitignore directories

- .github/CODEOWNERS
- .github/workflows/test_definitions.yml
> Automatically merge dependabot PRs

- .github/CODEOWNERS
> Remove ubcsailbotsoftware as codeowner

- .github/workflows/test_definitions.yml
- Branch protection rules prevent merge commits; change to squash
> Fix merge-dependabot-pr job

- .devcontainer/.dockerignore
- .gitignore
- README.md
- sailbot.code-workspace
- If the workspace file is in the root of the repository, VS Code will automatically prompt to open it
- Markdown link check will fail in this PR before it is merged in
> Move vs code workspace file to repo root

- .devcontainer/devcontainer.json
- Before was just installing the style
- Extension pack gives all functionality that GitHub-flavored markdown supports (mermaid diagrams, footnotes, etc.)
> Install github markdown extension pack

- .github/workflows/test_definitions.yml
- .markdown-link-check.json
- .markdownlint.json
- Use sailbot workspace configuration files
- Fix markdown link check bug where it always checked out sailbot workspace instead of input repository
> Update markdown linters

- .devcontainer/devcontainer.json
- sailbot.code-workspace
See commit names and file diff
> VS Code Infrastructure Update

- .github/workflows/test_definitions.yml
- Want to run colcon-test on all ROS packages in custom_interfaces PR to resolve any breaking changes in other repositories
> Enable VCS in custom_interfaces CI

- .markdown-link-check.json
- .markdownlint.json
> Markdown linter configuration fixes

- .devcontainer/Dockerfile
- .devcontainer/base-dev/base-dev.Dockerfile
- Resolves #227 
I added a command to install flask in the dockerfile, as the global path GUI in local_pathfinding uses the flask library.
To verify, I ran the rebuild container command, reloaded the window, and ran `flask --version` in the terminal. The version of flask installed was printed so the library was successfully added.
I followed the steps in [this README file](https://github.com/UBCSailbot/sailbot_workspace/blob/0d214e9597e6d807d12fef7b7383c578712fa0f3/.devcontainer/base-dev/README.md)
> Added flask dependency to the container

- .devcontainer/deployment/helpers/setup_can.sh
- Configures CAN on boot for raspberry Pi
- Pulled the branch on the raspberry Pi, rebooted, and it worked.
-
> Update setup_can script

- .devcontainer/devcontainer.json
- Resolves #240 
added a line to .devcontainer.json to install the geo data viewer extension for VS Code upon container rebuild.
This extension will be helpul for quickly viewing `.geo.json` files.
-  After making the change, I rebuilt the container and the extension was installed and worked correctly
[Info about Geo Data Viewer](https://marketplace.visualstudio.com/items?itemName=RandomFractalsInc.geo-data-viewer)
> Add GeoJSON viewer VS Code Extension

- .devcontainer/devcontainer.json
- Resolves #236 
Removed GiHub Copilot extension and a phantom GitHub issues/PR extension.
- Check that Github Copilot extension is not installed.
- None
> Devcontainer: Comment out Github Copilot extension

- src/network_systems/functions.cmake
- src/network_systems/lib/CMakeLists.txt
- src/network_systems/lib/net_node/CMakeLists.txt
- src/network_systems/lib/net_node/inc/net_node.h
- src/network_systems/lib/net_node/src/net_node.cpp
- src/network_systems/lib/sailbot_db/src/sailbot_db.cpp
- src/network_systems/projects/can_transceiver/src/can_transceiver_ros_intf.cpp
- src/network_systems/projects/example/src/cached_fib_ros_intf.cpp
- src/network_systems/projects/local_transceiver/CMakeLists.txt
- src/network_systems/projects/local_transceiver/inc/at_cmds.h
- src/network_systems/projects/local_transceiver/inc/local_transceiver.h
- src/network_systems/projects/local_transceiver/src/local_transceiver.cpp
- src/network_systems/projects/local_transceiver/src/local_transceiver_ros_intf.cpp
- src/network_systems/projects/local_transceiver/test/test_local_transceiver.cpp
- src/network_systems/projects/mock_ais/src/mock_ais_ros_intf.cpp
- src/network_systems/projects/remote_transceiver/src/remote_transceiver_ros_intf.cpp
- src/network_systems/ros_info.txt
- src/network_systems/scripts/README.md
- src/network_systems/scripts/http_echo_server.py
The migration missed the latest 2 commits in the old network_systems repository
-
> Latest NET Migration Changes

- .devcontainer/website/website.Dockerfile
Upgrade the Node.js version from v18 to v20 on the base image of the website. 
- Ran all tests on the website, nothing fails  
- Reran the simulation and tinkered around with the UI, everything is working fine 
- All checks have passed 
-
> Upgrade Node.js version from v18 to v20

- sailbot.code-workspace
- src/network_systems/scripts/gen_ros_info.py
- Lint script paths were broken by a github action directory structure change
- Updated workspace file to reflect new paths
- Also a small lint fix for a NET file
-
> Fix Lint Tasks

- .devcontainer/docs/README.md
- .devcontainer/website/README.md
- docs/current/sailbot_workspace/how_to.md
- docs/reference/markdown.md
- mkdocs.yml
- src/boat_simulator/README.md
- src/controller/README.md
- src/custom_interfaces/README.md
- src/local_pathfinding/README.md
- src/network_systems/README.md
There were a couple places that still referenced the old repositories. This PR either updates the url or deletes them
> Update links to deprecated sub-repositories

- src/network_systems/config/local_transceiver/local_transceiver_template.yaml
- src/network_systems/launch/main_launch.py
- src/network_systems/projects/local_transceiver/src/local_transceiver_ros_intf.cpp
- Resolves issue #272 
- Added modes and config file for local transceiver
- ROS2 publisher and subscriber tutorial: https://docs.ros.org/en/humble/Tutorials/Beginner-Client-Libraries/Writing-A-Simple-Cpp-Publisher-And-Subscriber.html
- https://docs.ros.org/en/humble/Tutorials/Beginner-CLI-Tools/Understanding-ROS2-Topics/Understanding-ROS2-Topics.html#ros2-topic-pub
> [NET] Local Transceiver: ROS modes and config file

- .github/CODEOWNERS
> Add Eric to CODEOWNERS

- .devcontainer/docs/docs.Dockerfile
- .github/workflows/docs.yml
- docs/requirements.txt
- Pin docs dependencies and delete redundant ones
- Run docs CI in container
- Integrate docs-build job into docs-deploy
> Update docs site infrastructure

- .github/workflows/docs.yml
- Continuation of #354 
- Still need to push the deletion of docs versions because delete and deploy steps run on different events
- Hopefully the added `git fetch` before pushing will resolve any push conflicts
> Add back pushing deleting docs version

- .github/workflows/docs.yml
- Continuation of #355 
- Still getting push conflicts
> Another attempt to resolve docs-update push conflicts

- .github/workflows/docs.yml
- Continuation of #356 
- Specify to merge if branches diverge (before nothing was specified and it wasn't sure what to do)
> Hopefully this actually fixes docs-update push conflicts

- .github/workflows/docs.yml
- Continuation of #357 
- When I tried to run the command locally I noticed that it was prompting for username and password on git push; hopefully this fixes that
> Authenticate inside container for docs-update

- .github/workflows/docs.yml
- Continuation of #358 
- Try an alternative way of getting the token
> Change authentication method

- .github/workflows/docs.yml
- Continuation of #359 
- Trying to fix this nondescript error: https://github.com/UBCSailbot/sailbot_workspace/actions/runs/8576346364/job/23507156780#step:5:14
> Wait for docs to deploy before deleting

- .github/CODEOWNERS
Merge in after all other PR's by graduating members are merged. Then I will make a release
> Make new leads codeowners

- src/website/lib/redux/middleware.ts
- src/website/stores/AISShips/AISShipsReducers.ts
- src/website/stores/GenericSensors/GenericSensorsReducers.ts
- src/website/stores/GlobalPath/GlobalPathReducers.ts
- src/website/stores/LocalPath/LocalPathReducers.ts
- Fixed Initial State for Redux Reducers to Prevent Compilation Errors
- Website compiles and builds properly
-
> Fixed Redux Reducers Initial State

- .gitignore
Added src/website/tests/node_modules and settings.json to the .gitignore file to ensure these are not tracked by git.
CI passes
Slack Reference:
https://ubcsailbot.slack.com/archives/C042XBRFBKJ/p1716044689558669
> Add website/tests/node_modules and settings.json to .gitignore

- src/website/lib/redux/logUtils.ts
- src/website/lib/redux/middleware.ts
- src/website/pages/index.tsx
- Resolves #293 
- Created `logUtils.ts` with the `clearLogsPeriodically` function that clears the console every minute.
-
> Fixed DB Polling Lag

- src/boat_simulator/boat_simulator/common/constants.py
- src/boat_simulator/boat_simulator/nodes/physics_engine/model.py
- src/boat_simulator/boat_simulator/nodes/physics_engine/physics_engine_node.py
- Resolves #424 
- Added 'mass' and 'inertia' attributes to BoatProperties class and updated the BOAT_PROPERTIES instance to include these values.
- Replaced second and third parameters in the initialization of self.__boat_state with BOAT_PROPERTIES.
> Add 'mass' and 'inertia' properties to BoatProperties

- scripts/test.sh
- src/network_systems/projects/remote_transceiver/test/test_remote_transceiver.cpp
- src/network_systems/scripts/README.md
- src/network_systems/scripts/rockblock_web_server.py
Implementation of a virtual RockBlock web server the remote transceiver uses to send MT messages. 
Tested by sending sample requests to the server through remote transceiver unit tests
> Add virtual rockblock web server

- src/boat_simulator/boat_simulator/nodes/physics_engine/fluid_generation.py
- src/boat_simulator/tests/unit/nodes/physics_engine/test_fluids.py
- src/global_launch/config/README.md
- src/global_launch/config/globals.yaml
- Resolves #447 by replacing 3D fluid vectors with 2D vectors 
- Fixes unit tests which used 3D fluid vectors to use 2D vectors
- Ran boat simulator tests and all passed, ran roslaunch and nothing crashed
> Update Fluid Generator to Produce 2D Fluids

- src/website/views/components/BoatCompass/BoatCompass.tsx
> fix compass bug

- .devcontainer/docker-compose.yml
- scripts/deployment/start_containers.sh
Upgraded MongoDB container from 4.4 to 7.0 due to a compatibility issue between MongoDB 4.4 and featureCompatibilityVersion 7.0.
This issue prevented the MongoDB container from starting, requiring the upgrade to resolve it.
-
> updated mongodb to 7.0

- src/network_systems/projects/local_transceiver/src/local_transceiver_ros_intf.cpp
- Runs virtual iridium script when local transceiver is started in DEV mode
> Run virtual iridium when starting local transceiver in DEV mode

- docs/current/sailbot_workspace/usage/setup.md
> Updated docker url

- src/local_pathfinding/.gitignore
- src/local_pathfinding/launch/main_launch.py
- src/local_pathfinding/local_pathfinding/mock_ais_node.py
- src/local_pathfinding/setup.py
- src/network_systems/projects/local_transceiver/inc/at_cmds.h
- src/network_systems/projects/local_transceiver/src/local_transceiver.cpp
- src/network_systems/projects/local_transceiver/test/test_local_transceiver.cpp
- src/website/views/components/DropDown/DropDown.module.css
- Resolves #476
Created a basic mock ais node that publishes a constant AIS ship to the ROS network.
> Creating Basic Mock AIS Node

- README.md
Fixed a dead link in the Readme so we can get green checkmarks back ✅
- CI
> Fixed dead link in Readme

- scripts/test.sh
To speed up the test task, the test task will only execute NET related tasks if either all packages are being tested or just NET.
Put NET specific tasks inside an IF block in `test.sh`
- Ran test package local_pathfinding and test all and verified the desired behaviour.
> Only complete NET related test tasks if testing all or just NET

- src/local_pathfinding/test/test_global_path.py
> commented out get_pos unit test. Its not a unit test

- .github/CODEOWNERS
Add Sean to CODEOWNERS for pathfinding
> Add Sean to CODEOWNERS for pathfinding

- src/local_pathfinding/local_pathfinding/coord_systems.py
- src/local_pathfinding/local_pathfinding/global_path.py
- src/local_pathfinding/local_pathfinding/local_path.py
- src/local_pathfinding/local_pathfinding/node_mock_ais.py
- src/local_pathfinding/local_pathfinding/node_mock_global_path.py
- src/local_pathfinding/local_pathfinding/node_navigate.py
- src/local_pathfinding/local_pathfinding/objectives.py
- src/local_pathfinding/local_pathfinding/obstacles.py
- src/local_pathfinding/local_pathfinding/ompl_path.py
- src/local_pathfinding/test/test_coord_systems.py
- src/local_pathfinding/test/test_local_path.py
- src/local_pathfinding/test/test_objectives.py
- src/local_pathfinding/test/test_ompl_path.py
- Change `LocalPath.waypoints` to type `List[HelperLatLon]`
- Change `LocalPathState.global_path` to type `Path`
- Checked unit tests; no changes required
- Tests pass (hopefully)
> Fix typing in LocalPath.py

- src/local_pathfinding/local_pathfinding/node_mock_ais.py
- Adds to #476 
- Updated the Mock AIS Node to allow for addition and removal of AIS ships through a CSV file during runtime. 
- Manual verification that the addition / removal of a row in the csv file changes the output logs.
> Implemented ability to add or remove AIS ships with CSV

- src/local_pathfinding/launch/main_launch.py
- src/local_pathfinding/local_pathfinding/node_navigate_observer.py
- src/local_pathfinding/setup.py
A basic observer that subscribes to the `local_path` topic.
The node only launches when running in development mode.
> Navigate Observer Node

- src/website/.env.production
- src/website/lib/redux/middleware.ts
- src/website/package-lock.json
- src/website/package.json
- src/website/views/components/Maps/Maps.tsx
> [WEB] Fixed Map Loading Issue on Production Environment

- src/custom_interfaces/msg/DesiredHeading.msg
- src/network_systems/projects/can_transceiver/inc/can_frame_parser.h
- src/network_systems/projects/can_transceiver/src/can_frame_parser.cpp
- src/network_systems/projects/can_transceiver/test/test_can_transceiver.cpp
- src/network_systems/projects/local_transceiver/test/test_local_transceiver.cpp
- Partially Resolves #462
This merge updates existing CAN frames to changes made to the CAN frames documentation. Adam will make another merge for new frames that were added.
- Updated and utilized existing unit tests for CAN frame parsing
- N/A
> #462 Updating existing CAN frames

- .github/CODEOWNERS
make Jing and Vaibhav get merge permissions
> Update CODEOWNERS to make Jing and Vaibhav net owners

- src/network_systems/projects/can_transceiver/src/can_frame_parser.cpp
- src/network_systems/projects/can_transceiver/src/can_transceiver_ros_intf.cpp
> Added desired heading and sailcmd callback

- src/network_systems/projects/can_transceiver/src/can_frame_parser.cpp
- src/network_systems/projects/can_transceiver/src/can_transceiver_ros_intf.cpp
- Resolves #595 
- Updates battery toString message to include current
- fix AIS ships ros interface so it publishes now
- Manual testing from #595
> Can frame updates from manual testing

- src/network_systems/projects/can_transceiver/src/can_transceiver_ros_intf.cpp
> improve vague logging when constructing an out of range can frame

- src/network_systems/projects/can_transceiver/src/can_transceiver.cpp
- src/network_systems/projects/can_transceiver/src/can_transceiver_ros_intf.cpp
- Resolves #601 
Enable manual mode which prevents software from sending CAN messages. All other ROS functions will still work.
> can manual mode ros parameter

- src/network_systems/projects/local_transceiver/src/local_transceiver_ros_intf.cpp
- Resolves #618 
- Production mode initialization was missing from local transceiver, this commit implements it.
> Implement local transceiver prod mode

- .github/workflows/docs.yml
> Adding Workflow Dispatch as a Docs Workflow Trigger

- .github/workflows/docs.yml
- .markdown-link-check.json
- .markdownlint.json
- scripts/deployment/README.md
- src/virtual_iridium/README.md
- Resolves #626 
- Reran the Docs Workflow and passed successfully. 
-
> Fixed Docs Workflow Linting and Dead Links Issue 

- .devcontainer/devcontainer.json
- sailbot.code-workspace
The old ROS extension we were using in VSCode is now deprecated. I have now switched to using the new version of the extension made by Ranch Hand Robotics LLC.
- Devcontainer builds successfully and the new extension is installed in the workspace.
> Updated VSCod ROS extension from the deprecated one to the new one

- src/local_pathfinding/local_pathfinding/visualizer.py
- Commented out the animated plot planning
- Made the live plot full screen
> removed animated plot and made the live plot fullscreen
