- .devcontainer/Dockerfile
- .devcontainer/base/raye/install-raye-dependencies.bash
- .devcontainer/dev/Dockerfile
The repo that we used for libspot (raye pathfinding dependency) just became deprecated. This causes `sudo apt update` to error, in turn causing our CI to fail.
What I did
- Updated the `base:raye` dockerfile to use a different repo that works
- Since this image takes 10 hours to build, there isn't a need to update it, I didn't
- Removed the deprecated repo in the `dev` dockerfile so that `sudo apt update` is error free
- Remove this section if `base:raye` is rebuilt
> Resolve deprecated raye dependency

- .devcontainer/README.md
- .devcontainer/dev/README.md
- .devcontainer/devcontainer.json
- README.md
Verify that x11 forwarding of GUI apps works for all operating systems. Can test by uncommenting the ROS tutorial dependencies, rebuilding the container, and running `ros2 run turtlesim turtlesim_node`.
I tested that it works on native Ubuntu 22.04
I tested that it works on Windows 11 WSL 2 Ubuntu 22.04
@Harvir14 please update the README with the steps required to get it working on Windows 10
@eomielan I added some better instructions for MacOS. Please run through them and check the box below if it works
~~@hhenry01 try out this branch to see if it solves your X11 problems~~ it won't lol
To Do's
> Fix x11 forwarding and revamp setup instructions

- .github/actions/lint/run.sh
- .github/actions/test/run.sh
- .github/workflows/regression-tests.yaml
- Resolves #67 
The move to sub-team repo specific CI disabled the use of VCS in the CI flow. For regression tests, we want to re-enable this so that we can verify that the main branch for all sub-team repos is working.
- In intermediary commits, I changed the regression test yaml file to run on push. It worked and the final commit switched it back to weekly.
> Enable VCS cloning for regression tests

- .devcontainer/Dockerfile
- .devcontainer/base/base.Dockerfile
- .devcontainer/base/build-base.sh
- .devcontainer/dev/build-dev.sh
- .devcontainer/dev/dev.Dockerfile
- .github/workflows/build-dev-image.yaml
- .github/workflows/tests.yaml
Renamed dev container dockerfile name but did not update build dev image workflow accordingly
> Fix build dev image wokflow

- .clang-tidy
Disables a check in the .clang-tidy file that causes the network-systems build to fail if the ROS publish function is used.
> Disable 'Move' clang-tidy check

- .devcontainer/devcontainer.json
- .github/release.yml
- devcontainer.json format was updated since I last opened the workspace
- Move bug section to beginning because I want PR's with multiple labels including bug to go in the bug section
- Remove infra section because this whole repo is infra
- Rename workflows section to be consistent with other sections
- `.devcontainer/` -> Dev Container Configuration Changes
- `.github/` -> GitHub Configuration Changes
- `.vscode/` -> VS Code Configuration Changes
> Fix VS Code config location and release notes template

- .github/workflows/tests.yaml
Reference: https://docs.github.com/en/actions/using-jobs/using-concurrency#example-only-cancel-in-progress-jobs-or-runs-for-the-current-workflow
> Cancel in-progress runs for the current workflow

- .github/workflows/build-images.yml
- .github/workflows/tests.yml
- README.md
Rebuild Docs on push to main, as it uses snippets of files from this repo. Also updated and renamed the token: they were generated using the ubcsailbotsoftware GitHub account
- Merge after the docs PR to verify that this PR works: README contents should change
> Rebuild Docs on push to main

- .devcontainer/deployment/README.md
- .devcontainer/deployment/start_container.sh
- .devcontainer/devcontainer.json
- .devcontainer/docker-compose.yml
Make the dev container use docker compose. Previously, it was built on `.devcontainer/Dockerfile`. Now it is built on `.devcontainer/docker-compose.yml`, which builds the dockerfile. Using docker compose allows the dev container to run multiple images.
- https://github.com/devcontainers/templates/tree/main/src/javascript-node-mongo
> Use docker compose

- .github/workflows/test_definitions.yml
- .github/workflows/tests.yml
Follow up of #122.
Could not detect `GH_TOKEN` environment variable: https://github.com/UBCSailbot/sailbot_workspace/actions/runs/5073248488/jobs/9112013165. This is because secrets are not passed to the reusable workflow.
Once this PR is merged in, will need to update caller workflows:
> Fix rebuild docs part 2

- .devcontainer/deployment/start_container.sh
Deployment container should have all the same run arguments as the dev container. Previously we were missing the ones from the template repository, https://github.com/athackst/vscode_ros2_workspace:
https://github.com/UBCSailbot/sailbot_workspace/blob/ac897795ceed0381c6f484a90d233eb3040729fd/.devcontainer/docker-compose.yml#L18-L23
@hhenry01 FYI
> Add template repo run arguments to deployment container

- .devcontainer/Dockerfile
- .devcontainer/base-dev/base-dev.Dockerfile
- .devcontainer/config/sailbot_workspace.code-workspace
- .devcontainer/devcontainer.json
- .github/workflows/test_definitions.yml
- .github/workflows/tests.yml
- setup.sh
- src/new_project.repos
Python infrastructure improvements made:
- Format on save
- Fix build warning
- Change line length to 99
- Align ament lint tasks and github action job
- Remove ament_pep257 linter: I don't like the docstrings format it enforces; use Google docstrings template generated by extension instead
- Configure timezone to "America/Vancouver"
- Customize ROS log format
- Tested in conjunction with writing the skeleton code for the local pathfinding repository
> Add local pathfinding repo and improve python infra

- .devcontainer/Dockerfile
- .devcontainer/base-dev/update-bashrc.sh
Thanks to @Krithik1 for finding this bug
When building from scratch in a fresh dev container would get this error:
To resolve this we have to source ROS in all cases. The ROS overlay is only available after building, so if the overlay doesn't exist we should source the underlay.
> Source ROS underlay if overlay not found

- .devcontainer/Dockerfile
- .devcontainer/base-dev/base-dev.Dockerfile
- .devcontainer/website/website.Dockerfile
MongoDB shell and command line tools was installed in website container when it should have been installed in Sailbot Workspace. This way you can interact with mongodb from a Sailbot Workspace shell.
Had to refactor the installation steps from Debian to Ubuntu. Also installed `mongodb-database-tools` on arm (this package wasn't available for arm in Debian).
Thanks @dk1702 for catching this
> Migrate MongoDB CLI to local-base image

- .github/workflows/test_definitions.yml
- .github/workflows/tests.yml
In other repositories, VCS should be disabled. However, VCS seems to be running in `colcon-test`, `ament-lint`, and `clang-tidy`: https://github.com/UBCSailbot/local_pathfinding/actions/runs/5365212299
This is due to the fact that `github.event.repository.name` evaluates to the caller workflow's repository, not the reusable workflow's.
> Fix VCS enabled in other repositories

- setup.sh
I think that it is desirable for the setup task to try to switch to the branches in new_project.repos. It will error out if there are conflicts. The setup task should only be run when you first setup the workspace or want to switch to the default branches.
> Revert setup skipping existing repositories

- .devcontainer/config/sailbot_workspace.code-workspace
Add path to python interpreter in workspace config file for black formatted. Without it, black would try to make assumptions on which interpreter to use and may get it wrong.
> Specify interpreter path for python extensions

- .devcontainer/Dockerfile
- .devcontainer/base-dev/base-dev.Dockerfile
- .devcontainer/pre-base/build-pre-base.sh
- .devcontainer/pre-base/pre-base.Dockerfile
- Since #161, base/dev image build times went from 17 min to 2 hrs+
- The cause of this was building `mongo-cxx-driver` from source
- Since this is needed for everything, moved to the pre-base image
- Effect: base/dev image build times are back to 17 min, and reduced their size by 100mb
> Fix base/dev image long build times

- .devcontainer/Dockerfile
- .devcontainer/base-dev/base-dev.Dockerfile
- .devcontainer/config/sailbot_workspace.code-workspace
- .devcontainer/devcontainer.json
- .github/actions/ament-lint/run.sh
- .github/workflows/test_definitions.yml
- src/global_launch/main_launch.py
- Relevant issue: https://github.com/UBCSailbot/sailbot_workspace/issues/39
- Install `mypy` in base container and create vscode task `type check`
- The [mypy extension](https://github.com/microsoft/vscode-mypy) recently had an install release. It worked in the workspace with some success, but the linter sometimes wouldn't run automatically when a file opened like the documentation said. I commented out the vscode configuration for now and settled on creating a vscode task instead.
- [Patrick] Seems to be working now, so enabled
Once this is merged, create a new minor release
> Configure mypy in workspace

- .devcontainer/config/sailbot_workspace.code-workspace
- build.sh
- Cause after #179 it's not faster anymore
> Remove quick build flag

- .github/actions/test/run.sh
- test.sh
- Start a virtual iridium server whenever test.sh is ran and the src/network_systems folder exists
- Needed for https://github.com/UBCSailbot/network_systems/pull/52 and later local/remote transceiver and integration tests
-
> Run virtual iridium before tests

- .github/workflows/tests.yml
Workflows may be triggered from this repository or others. We don't want these runs to cancel each other, and instead want all runs to complete
> Don't cancel in-progress jobs

- test.sh
- New dependency of NET tests: https://github.com/UBCSailbot/network_systems/pull/52
- Exit code of 0 is returned when all tests pass
- Tested in https://github.com/UBCSailbot/local_pathfinding/pull/47
- Exit code of 1 is returned when a test fails
- Correct exit code is returned when network_systems is not present (virtual_iridium is never run in this case)
> Start and kill virtual iridium in test.sh

- .github/workflows/test_definitions.yml
- Use `inputs.repository` for repository name
- Use ref instead of sha (human readable)
- Clean up
> Fix sailbot workspace ref for other repositories

- .devcontainer/Dockerfile
- .devcontainer/base-dev/base-dev.Dockerfile
This PR adds rapidyaml as a static library for use in the diagnostics app. 
Link to rapidyaml: https://github.com/biojppm/rapidyaml.git
> Add rapidyaml as a static library

- .github/workflows/test_definitions.yml
- The jobs `rebuild-docs` and `run-sailbot-workspace-ci` run workflows in other repositories
- I noticed that if these workflows fail, the jobs still pass
- Fixed this bug by adding `--exit-status` argument to `gh run watch`
- https://cli.github.com/manual/gh_run_watch
> CI fails if called workflow fails

- .github/workflows/test_definitions.yml
- .github/workflows/tests.yml
- Need to create identical action and dependabot secret
- Dependabot secret cannot have dashes
- Rename secret to `PAT_TOKEN`
- https://docs.github.com/en/code-security/dependabot/working-with-dependabot/automating-dependabot-with-github-actions#accessing-secrets
> Rename reusable workflow secret

- .clang-tidy
Disable the `bugprone-infinite-loop` check for clang-tidy. This check turned out to be extremely slow for iterable data structures, even when there was no loop in network_systems code.
Isolated the specific check using the command: `clang-tidy -p build/  src/network_systems/projects/can_transceiver/src/can_transceiver_ros_intf.cpp --enable-check-profile`
- https://clang.llvm.org/extra/clang-tidy/checks/bugprone/infinite-loop.html
> Remove clang-tidy Infinite Loop Check to Reduce Runtime

- src/global_launch/main_launch.py
The controller was added to the list of launchable ROS packages in the global launch file. This PR is closely related to the following PR for the controller: https://github.com/UBCSailbot/controller/pull/10
- The entire system, including the controller, is started. The desired debug statements are observed from the controller when the `log_level` argument is set to `debug`.
> Add Controller to Global Launch File

- src/global_launch/main_launch.py
- Resolves #215 
Allows us to specify multiple `.yaml` files when doing `ros2 launch`. What this does is allow us to specify a base configuration and allow for overriding of specific nodes. For example, if we do `ros2 launch network_systems main_launch.py config:=config1.yaml,config2.yaml`, then:
1. globals.yaml is loaded and processed
2. config1.yaml is loaded and overrides any duplicate parameters with globals.yaml
3. config2.yaml is loaded and override previous duplicate parameters
Non-duplicate parameters are unchanged.
To take advantage of this overriding structure, main_launch.py in subteam repos should be updated such that:
- inside `get_global_launch_arguments()` assign a global variable `global_launch_config = module.GLOBAL_LAUNCH_CONFIG`
- In each `get_x_description()`, assign …
> Support multiple global launch configs

- .github/workflows/test_definitions.yml
- In #218 the extract-metadata job is run for the markdown linter jobs. This PR fixes a bug where extract-metadata didn't run when only markdown linters where run (not ROS linters or clang tidy)
> Run extract-metadata job when needed

- src/global_launch/config/README.md
- src/global_launch/config/globals.yaml
Linked to Issue [49](https://github.com/UBCSailbot/local_pathfinding/issues/49) in Local Pathfinding.
The purpose was to set some parameters, for the mock global path node, in the global params file rather than in the node's python file.
The added parameters are:
1. global_path_filepath
2. interval_spacing
1. Run the global or local pathfinding launch file with development mode (default)
```
ros2 launch local_pathfinding main_launch.py
```
2. In a different terminal run some ros2 param commands
```
ros2 param get /mgp_main global_path_filepath
ros2 param set /mgp_main global_path_filepath /workspaces/sailbot_workspace/src/local_pathfinding/global_paths/path_2.csv
```
- [Link](https://github.com/UBCSailbot/local_pathfinding/pull/61) to the PR for this issue.
> Addition of Global Parameters for Mock Global Path Node

- src/global_launch/config/README.md
- src/global_launch/config/globals.yaml
Linked to Issue [49](https://github.com/UBCSailbot/local_pathfinding/issues/49) in Local Pathfinding.
The purpose was to add a parameter to determine whether the generate_path function in node_mock_global_path.py should write a generated path to a new csv file.
The added parameter is:
`write`
1. Run the global or local pathfinding launch file with development mode (default)
```
ros2 launch local_pathfinding main_launch.py
```
2. In a different terminal run some ros2 param commands
```
ros2 param get /mgp_main global_path_filepath
ros2 param set /mgp_main global_path_filepath /workspaces/sailbot_workspace/src/local_pathfinding/global_paths/path_2.csv
```
- [Link](https://github.com/UBCSailbot/local_pathfinding/pull/61) to the PR for this issue.
> Added a write parameter for the Mock Global Path node

- .devcontainer/devcontainer.json
- .gitignore
- src/global_launch/config/README.md
- src/global_launch/config/globals.yaml
- Update the `globals.yaml` file to align with the changes introduced by the new data collection node for the boat simulator.
> Add configuration for data collection node

- run_virtual_iridium.sh
- The default argument for `--webhook-server-endpoint` has the incorrect format. Virtual Iridium crashes when running the Local Transceiver without this fix.
- @Jng468 you'll need to pull from sailbot_workspace main after this is merged.
-
> Fix run_virtual_iridium.sh

- .github/dependabot.yml
Security updates aren't grouping
> Comment out grouped dependabot updates

- src/local_pathfinding/test/test_ompl_path.py
Previously we were using bitstar. Informed tree planners require a cost to go heuristic which we do not provide, which cause a warning to appear in our tests. I have switched the planner used in our tests to rrtstar until we have implemented the heuristic (@akash-venkateshwaran is exploring this in his project).
> Use rrtstar planner in tests

- .devcontainer/website/website.Dockerfile
- src/website/package-lock.json
- src/website/package.json
A weird side-effect occurs in the `package-lock.json` file when we run `npm install` using the header `--legacy-peer-deps`. The header is no longer needed, so I'm removing it from the Dockerfile for the website.  
Also, I'm setting next.js to a fixed version. It's not good to install the "latest" version on every build - we want control over exactly which packages update and how that update happens.
- Rebuilt the containers, the website still functions fine.
> Remove legacy-peer-deps header when installing node packages for website

- .devcontainer/website/website.Dockerfile
- Resolves #334 
Changing the base image to node-alpine. Alpine is better as it's faster and more lightweight compared to the official node images (which come with preset libraries). 
- Tests all pass.
- Website functions fine. 
- https://hub.docker.com/_/node
- https://stackoverflow.com/questions/53024267/docker-are-node-alpine-images-at-the-end-smaller-than-full-node-images
> Update website base image to node:20-alpine

- src/network_systems/projects/remote_transceiver/inc/remote_transceiver.h
- src/network_systems/projects/remote_transceiver/test/test_remote_transceiver.cpp
- Resolves #231 
- Increase the timeout allowed between POST and checking.
- Reran CI 10 times
-
> Fix Remote Transceiver Test Failures

- .github/workflows/docs.yml
- After #351 the docs deploy and delete jobs run slower since they have to pull and run in a container
- Since they both ran when a PR is merged (one when PR is closed, another on push to main), there was often push conflicts: https://github.com/UBCSailbot/sailbot_workspace/actions/runs/8552838434/job/23434784662#step:6:17
- To resolve this, do everything in one job, and only push on deploy
> Combine docs-deploy and docs-delete jobs

- src/local_pathfinding/local_pathfinding/global_path.py
- src/local_pathfinding/test/post_server.py
- src/local_pathfinding/test/test_global_path.py
- Resolves #363 
Moved the test post_server from port 8081 to 8085.
Also refactored the test files a bit so that we only need to change one line to change the test port again if needed.
- Ran the test task, but the local path tests might be running before NET on my machine
> Changed Port for Posting Global Paths in Tests

- .github/CODEOWNERS
- src/website/README.md
- Resolves #378 
Made some slight updates to our README to include some new details regarding our env vars and tech stack. The existing documentation for Typescript, React, Redux, etc. is explained pretty well and there's nothing specific to the website that will require further explaination. I attached links to those.
(EDIT: Also adding Jordan as the codeowner for the website here) 
- This PR will need to be merged after https://github.com/UBCSailbot/sailbot_workspace/pull/366 is merged in. 
-
> Update Website README

- src/controller/tests/unit/wingsail/test_controllers.py
- Fixed an issue with one of the controller tests that was giving a warning:
- It seems that this issue was caused by one of the variable names starting with 'test', leading pytest to mistakenly try to collect it as a test or fixture.
- Re-ran controller unit tests.
> Fix warning from test_controllers unit test

- src/boat_simulator/boat_simulator/nodes/physics_engine/physics_engine_node.py
- Added instance variables to the physics engine node for tracking the boat state, and generating winds and current vectors.
> Add instance variables to physics node

- .github/dependabot.yml
John wanted dependabot updates to be disabled for the website and for its dependencies to be updated manually (https://github.com/UBCSailbot/sailbot_workspace/issues/362), but my original implementation didn't work. Hopefully this PR fixes that. You can manually close https://github.com/UBCSailbot/sailbot_workspace/pull/408 or merge it in, up to you
> Fix disabling dependabot updates for website

- .markdown-link-check.json
The `docs.yml` workflow is failing because the following link returns a `403 Forbidden` repsonse when the link checker requests the website. 
[https://www.toptal.com/robotics/introduction-to-robot-operating-system](https://www.toptal.com/robotics/introduction-to-robot-operating-system)
A 403 response means the server understands the request but refuses to fulfill it.
The link works fine with a browser, so the maintainers of **Toptal** likely are blocking any user agents that are not web browsers.
Ie. this command returns 403 
`wget https://www.toptal.com/robotics/introduction-to-robot-operating-system`
and this command returns 200
`wget --user-agent="Chrome/58.0.3029.110" https://www.toptal.com/robotics/introduction-to-robot-o
perating-system`
We're not going to spoof user agents, …
> Resolved Markdown Link Check Failure by Accepting 403 Response as a Live Link

- mkdocs.yml
- The edit URI incorrect so it didn't open the right link; this PR should fix that
> Fix view and edit source links in docs site

- src/boat_simulator/boat_simulator/common/constants.py
- src/boat_simulator/boat_simulator/nodes/data_collection/data_collection_node.py
- src/boat_simulator/boat_simulator/nodes/physics_engine/fluid_generation.py
- src/boat_simulator/boat_simulator/nodes/physics_engine/model.py
- src/boat_simulator/boat_simulator/nodes/physics_engine/physics_engine_node.py
- src/boat_simulator/tests/unit/nodes/physics_engine/test_fluids.py
- src/global_launch/config/README.md
- src/global_launch/config/globals.yaml
This PR addresses the following issues and enhancements:
-Resolves dimension mismatches between 2D fluid generation and the expected 3D dimensions in the simulator.
- Adds configuration options for wind and current generation properties, including mean and covariance, in `globals.yaml`.
- Updates comments and certain properties within `BoatProperties` for clarity and accuracy.
> Simulator dimension mismatches & fluid generation config

- src/boat_simulator/boat_simulator/common/sensors.py
- src/boat_simulator/tests/unit/common/test_gps_sensor.py
- src/boat_simulator/tests/unit/common/test_wind_sensor.py
- Resolves #439 
-Resolved conflict between WindSensor and GPS classes and WindSensor and GPS ROS messages by renaming the classes
- Ran boat_simulator tests, tests passed for modified files (test_wind_sensor.py and test_gps_sensor.py)
> Resolve sensor and ROS message naming conflict

- src/boat_simulator/tests/unit/nodes/physics_engine/test_fluids.py
- This PR is to resolve warnings originating from the simulator fluid generation unit tests about `covariance is not positive-semidefinite`.
> Resolve simulator unit test warnings

- src/local_pathfinding/local_pathfinding/local_path.py
- src/local_pathfinding/local_pathfinding/ompl_path.py
- src/local_pathfinding/test/test_ompl_path.py
Local pathfinding would break when initializing the reference_latlon in `OMPLPath` as the global path was not initialized as None in the `LocalPathState`.  To fix that I just initialized global path to none and checked it when initializing the reference latlon.
-  Run the command `ros2 launch local_pathfinding main_launch.py` and ensured no errors was occuring.
> Global Path Bug

- docs/current/sailbot_workspace/usage/setup.md
- Dead link in setup instructions: https://docs.docker.com/desktop/faqs/linuxfaqs/#what-is-the-difference-between-docker-desktop-for-linux-and-docker-engine
- Replaced with https://www.docker.com/blog/how-to-check-docker-version
> Fix dead link in setup instructions

- sailbot.code-workspace
The markdown formatter currently defaults to 2-space indentation, while the linter expects 4-space indentation. This mismatch causes the Markdown lint CI to fail and makes it hard for users to address the issue, as the auto-formatter reverts changes back to 2 spaces.
- Updated the workspace settings to use the markdownlint configurations.
- Verified that the formatter now follows the linter's configuration and uses 4 spaces for indentation.
> Fix markdown formatter configuration

- .devcontainer/Dockerfile
- .devcontainer/base-dev/base-dev.Dockerfile
- .devcontainer/base-dev/update-bashrc.sh
- sailbot.code-workspace
- scripts/build.sh
- scripts/setup.sh
- scripts/test.sh
This PR optimized the build task, allowed for the test task to be run on individual packages, and also made some updates to `update-bashrc.sh` which will be used later once the new docker image is finished building.
- Ran both the test and build tasks and verified results
> Optimize Build Task and Allow Test Task to be Package Specific

- src/local_pathfinding/local_pathfinding/coord_systems.py
- src/local_pathfinding/test/test_coord_systems.py
This is just a helper function I'd like to use in my implementation of obstacle tracking by the OMPLPath module.
I created a function that converts a given shapely Polygon in XY coordinates to LatLon coordinates.
The purpose is to convert the XY state space into a LatLon region that can be used to then query for nearby land obstacles (which are all stored in LatLon)
- Created a unit test that uses the tried and true `latlon_to_xy` to verify the conversion of a poylgon.
> Created function to convert an XY polygon to a LatLon polygon

- src/network_systems/projects/local_transceiver/inc/at_cmds.h
- src/network_systems/projects/local_transceiver/src/local_transceiver.cpp
- src/network_systems/projects/local_transceiver/test/test_local_transceiver.cpp
- This PR is to restore the change to local transceiver which were overwritten by another PR
- Verified that messages can be received back-to-back
> NET: Local Transceiver, restore overwritten changes

- .github/workflows/docs.yml
- README.md
- Resolves #526 
I am just going to run the docs workflow much less frequently so we don't have to keep rerunning the action when it runs out of memory.
> Only run docs workflow when docs is modified plus once weekly

- src/local_pathfinding/local_pathfinding/node_navigate.py
Just uncommented one line to. Now the navigate node will actually report in any subscribed data hasnt been received yet now that mock nodes are ready.
> Report inactive subs instead of reporting all active by default

- src/custom_interfaces/CMakeLists.txt
- src/custom_interfaces/msg/HelperObstacle.msg
- src/custom_interfaces/msg/LPathData.msg
- src/local_pathfinding/local_pathfinding/node_navigate.py
We want the navigate node to publish all navigation data it has access to. This includes:
- global path
- local path
- gps
- windsensor
- AIS ships
- obstacles
- desired heading
Then our observer/visualizer node will subscribe to this message in order to access all the information available to the navigate node.
Update the specification of the LPathData msg to include all the above data.
This PR is just for creating the new msg type `HelperObstacle.msg` and editing the `LPAthDat.msg` type to include all navigation data.
To test the updated LPathData type compiled properly, I ran the following script
```
import custom_interfaces.msg as ci
def main():
local_path_data = ci.LPathData(
global_path=ci.Path(),
local_path=ci.Path(),
gps=ci.GPS(),
filtered_wind_sensor=ci.WindSensor(), …
```
> Update LPathData msg type and create new HelperObstacle msg type

- src/local_pathfinding/local_pathfinding/node_mock_ais.py
- Adds to #476 
- Updated the Mock AIS Node to update ship headings every `self.timer_period' based on rate of turn (ROT).
- Manual verification that heading changes by a correct amount every `self.timer_period' given an initial heading and rot.
> Added Self-update of Heading Based on ROT for Mock AIS Node

- src/local_pathfinding/local_pathfinding/objectives.py
- src/local_pathfinding/test/test_objectives.py
Removed two of the methods for the MinimumTurningObjective that we are not going to use.
All unit tests pass
Visual verification in the visualizer that the paths look pretty good, not too many turns.
> Change minimum turning objective to use heading-path method only

- src/local_pathfinding/local_pathfinding/node_mock_gps.py
- src/local_pathfinding/local_pathfinding/objectives.py
- src/local_pathfinding/test/test_objectives.py
- Resolves no issue (minor fix)
- Made updates to how get_sailbot_speed was used by converting apparent wind to true wind
- All tests passed and manual verification that the ros doesn't crash
> Pathfinding Mock GPS node fixed 
